
create database proyecto;
use proyecto;

create table usuarios(
U_ID int AUTO_INCREMENT,
U_TCUENTA VARCHAR(10),
USUARIO VARCHAR (20),
CLAVE VARCHAR (40),
CONSTRAINT PK_ID PRIMARY KEY (U_ID));


CREATE TABLE DATOS_USUARIO (
U_ID int AUTO_INCREMENT,
U_TCUENTA VARCHAR(20),
U_NOMBRE VARCHAR(30),
U_APELLIDOP VARCHAR(30),
U_APELLIDOM VARCHAR(30),
U_TELEFONO INT (12),
U_CELULAR  INT(14),
U_CORREO VARCHAR (50),
CONSTRAINT UNIQUE (U_CORREO),
CONSTRAINT FK_ID1 FOREIGN KEY (U_ID) REFERENCES USUARIOS (U_ID));



CREATE TABLE U_CHECADOR(
U_ID int AUTO_INCREMENT,
U_H_ENTRADA VARCHAR (20),
U_H_SALIDA VARCHAR (20),
CONSTRAINT FK_ID2 FOREIGN KEY (U_ID) REFERENCES USUARIOS (U_ID));



CREATE TABLE RESIDENTES (
R_ID VARCHAR (20),
R_ESTADO VARCHAR (10),
R_CODACCESO VARCHAR (20),
R_TRESIDENTE VARCHAR (15),
R_TCUENTA VARCHAR(20),
R_NOMBRE VARCHAR(30),
R_APELLIDOP VARCHAR(30),
R_APELLIDOM VARCHAR(30),
R_TELEFONO INT,
R_CELULAR  INT,
R_CORREO VARCHAR (50),
CONSTRAINT UNIQUE (R_CODACCESO),
CONSTRAINT UNIQUE (R_CORREO),
CONSTRAINT FK_R_ID PRIMARY KEY (R_ID));


CREATE TABLE VEHICULO(
R_ID VARCHAR (20),
R_TVEHICULO VARCHAR (15),
R_MARCA VARCHAR (25),
R_MODELO VARCHAR (25),
R_PLACAS VARCHAR (10),
R_VDEFECTOS VARCHAR (500),
CONSTRAINT UNIQUE (R_PLACAS),
CONSTRAINT FK_R_ID1 FOREIGN KEY (R_ID) REFERENCES RESIDENTES (R_ID));
 

CREATE TABLE HORARIO (
R_ID VARCHAR (20), 
L VARCHAR (20),
M VARCHAR (20),
MI VARCHAR (20),
J VARCHAR (20),
V VARCHAR (20),
S VARCHAR (20),
D VARCHAR (20),
CONSTRAINT FK_R_ID2 FOREIGN KEY (R_ID) REFERENCES RESIDENTES (R_ID));


CREATE TABLE BITACORA (
R_ID VARCHAR (20),
R_TVISITA VARCHAR (20),
R_H_ENTRADA VARCHAR (20),
R_H_SALIDA VARCHAR (20),
CONSTRAINT FK_R_ID3 FOREIGN KEY (R_ID) REFERENCES RESIDENTES (R_ID));
 




